# Generated by Django 3.2 on 2023-01-04 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_genretitle_genre_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre_title',
            old_name='genre',
            new_name='genre_id',
        ),
        migrations.RenameField(
            model_name='genre_title',
            old_name='name',
            new_name='title_id',
        ),
    ]
