# Generated by Django 3.2 on 2023-01-04 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20230104_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre_title',
            old_name='genre_id',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='genre_title',
            old_name='title_id',
            new_name='title',
        ),
    ]
