# Generated by Django 3.2 on 2023-01-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20230104_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titles',
            name='genre',
        ),
	migrations.AddField(
            model_name='titles',
            name='genre',
            field=models.ManyToManyField(related_name='genre', to='api.Genres'),
	),
        migrations.DeleteModel(
            name='Genre_Title',
        ),
    ]
