# Generated by Django 3.2 on 2023-01-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_titles_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='titles',
            name='genre',
            field=models.ManyToManyField(related_name='genre', to='api.Genres'),
        ),
    ]
