# Generated by Django 3.2 on 2023-01-04 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_titles_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titles',
            name='category',
        ),
        migrations.RemoveField(
            model_name='titles',
            name='genre',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Genres',
        ),
        migrations.DeleteModel(
            name='Titles',
        ),
    ]
