# Generated by Django 3.2 on 2023-01-10 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10, message='Введите значение от 1 до 10'), django.core.validators.MinValueValidator(1, message='Введите значение от 1 до 10')], verbose_name='Значение оценки'),
        ),
    ]
