# Generated by Django 3.2 on 2023-01-10 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20230110_2050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('category',)},
        ),
    ]
